import Vue from 'vue'
import './styles/quasar.styl'
import iconSet from 'quasar/icon-set/fontawesome-v5.js'
import lang from 'quasar/lang/pt-br.js'
import '@quasar/extras/roboto-font/roboto-font.css'
import '@quasar/extras/material-icons/material-icons.css'
import '@quasar/extras/fontawesome-v5/fontawesome-v5.css'
import {
  Quasar,
  QLayout,
  QHeader,
  QDrawer,
  QPageContainer,
  QPage,
  QToolbar,
  QToolbarTitle,
  QBtn,
  QIcon,
  QList,
  QItem,
  QItemSection,
  QItemLabel,
  QSeparator,
  QScrollArea,
  Ripple,
  QFooter,
  QCard,
  QCardSection,
  QCardActions,
  QTooltip,
  QForm,
  QInput,
  QDialog,
  QStep,
  QStepper,
  QSpace,
  QPopupProxy,
  QDate,
  QSelect,
  QStepperNavigation,
  QBreadcrumbs,
  QBreadcrumbsEl,
  QBtnDropdown,
  QTable,
  QTh,
  QTr,
  QTd,
  ClosePopup,
  QExpansionItem,
  QBadge,
  QChip,
  QAvatar,
  QBar,
  Dark,
  LoadingBar,
  Notify,
  QMenu,
  QBanner,
  QTab,
  QTabs,
  QSplitter,
  QTabPanels,
  QTabPanel,
  QSpinnerPie,
  QSpinnerAudio,
  QSpinner,
  QImg
} from 'quasar'

Vue.use(Quasar, {
  config: {
    Dark
  },
  components: {
    QBanner,
    QLayout,
    QHeader,
    QDrawer,
    QPageContainer,
    QPage,
    QToolbar,
    QToolbarTitle,
    QBtn,
    QIcon,
    QList,
    QItem,
    QItemSection,
    QItemLabel,
    QSeparator,
    QScrollArea,
    QFooter,
    QCard,
    QCardSection,
    QCardActions,
    QTooltip,
    QForm,
    QInput,
    QDialog,
    QStep,
    QStepper,
    QSpace,
    QPopupProxy,
    QDate,
    QSelect,
    QStepperNavigation,
    QBreadcrumbs,
    QBreadcrumbsEl,
    QBtnDropdown,
    QTable,
    QTh,
    QTr,
    QTd,
    QExpansionItem,
    QBadge,
    QChip,
    QAvatar,
    QBar,
    QMenu,
    QSplitter,
    QTabPanels,
    QTabPanel,
    QTab,
    QTabs,
    QSpinnerPie,
    QSpinnerAudio,
    QSpinner,
    QImg
  },
  directives: {
    Ripple,
    ClosePopup
  },
  plugins: {
    LoadingBar,
    Notify
  },
  lang: lang,
  iconSet: iconSet
})
LoadingBar.setDefaults({
  color: 'secondary',
  size: '3px',
  position: 'top'
})
